secret_key_base: qpWaZR0Y3JqDFrKRRcPtzxq4vTt82NZA9BZr1GEGXoo
port: 3000
name: blog_zero
log: "::Logger.new(STDOUT)"
log_level: "::Logger::INFO"
color: true
host: 0.0.0.0
port_reuse: false
process_count: (ENV[%(AMBER_PROCESS_COUNT)]? || 1).to_i
ssl_key_file:
ssl_cert_file:
redis_url: "redis://localhost:6379"
session:
  key: amber.session
  store: :signed_cookie
  expires: 0
secrets:
  description: Store your development secrets credentials and settings here.
  database: postgres://postgres:@pg:5432/blog_zero_development
